version: "3.8"
volumes:
  db-data:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - php
      - react
  php:
    build: ./server
    volumes:
      - ./server/src:/var/www/html
    depends_on:
      - db
  react:
    build: ./client
    volumes:
      - ./client:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 1234:5432
    volumes:
      - db-data:/var/lib/postgresql/data
