version: "3.8"
volumes:
  db-data:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - nodejs
      - react
  nodejs:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - db
  react:
    build: ./client
    volumes:
      - ./client:/app
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    hostname: db
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_manager
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
